version: '3'

services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/nginx-vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 82:80
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/etc/php.d/php.ini

    mysql:
        image: mariadb:10.1.43
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: 123
        ports:
            - 3306:3306
        volumes:
            - ./mysql_data:/var/lib/mysql
