version: '3'

services:
  php:
    build: 
      context: ./docker/web
    volumes:
      - ./src:/var/www
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
    environment: 
      WEBROOT: "/var/www/backend/web"
#      ENABLE_XDEBUG: 1
#      XDEBUG_CONFIG: 192.168.1.70
#      PHP_IDE_CONFIG: "serverName=stickers"
    ports:
      - 80:80
